export const GENERATE_ERROR_MSG = "GENERATE_ERROR_MSG";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const GENERATE_WARNING_MSG = 'GENERATE_WARNING_MSG';
export const CLEAR_WARNING = "CLEAR_WARNING";
export const GENERATE_SUCCESS_MSG = "GENEREATE_SUCCESS_MSG";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_EVERYTHING = "CLEAR_EVERYTHING";