export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const RECOVER_REQUEST = 'RECOVER_REQUEST';
export const RECOVER_ERROR = 'RECOVER_ERROR';
export const RECOVER_SUCCESS = 'RECOVER_SUCCESS';

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CLEAR_MSGS = 'CLEAR_MSGS';

export const SEND_VERIFICATION_EMAIL_REQUEST = "SEND_VERIFICATION_EMAIL_REQUEST";
export const SEND_VERIFICATION_EMAIL_SUCCESS = "SEND_VERIFICATION_EMAIL_SUCCESS";